### ISSUE TITLE
Success on Vernee Mix 2 (MT6757CD)

### ISSUE THREAD

**Issue by 808MT6757CD** [JunioJsv/mediatek-easy-root#13]
param1: 0x3000, param2: 0x10000, type: 4
Building symbol table
kallsyms_addresses pa 0x40d6b100
kallsyms_num_syms 65993, addr_count 65993
kallsyms_names pa 0x40dec100, size 815153
kallsyms_markers pa 0x40eb3200
kallsyms_token_table pa 0x40eb3b00
kallsyms_token_index pa 0x40eb3f00
Patching credentials
Parsing current_is_single_threaded
ffffffc0003382c0+50: ADRP x0, 0xffffffc0011ab000
ffffffc0003382c0+54: ADD xd, x0, 3488
init_task VA: 0xffffffc0011abda0
Potential list_head tasks at offset 0x360
comm swapper/0 at offset 0x618
Found own task_struct at node 1
cred VA: 0xffffffc0afe729c0
Parsing avc_denied
ffffffc0002d2dc8+24: ADRP x0, 0xffffffc00156c000
ffffffc0002d2dc8+28: LDR [x0, 2836]
selinux_enforcing VA: 0xffffffc00156cb14
Setting selinux_enforcingarmv8l machine
Retrying...
Retrying...
Retrying...
Retrying...
Could not set selinux
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
returned 0

**Comment by JunioJsv** [comment]
Topper 😀
