### ISSUE TITLE
Google Play Protect

### ISSUE THREAD

**Issue by Abdelrhman-AK** [JunioJsv/mediatek-easy-root#17]
Google Play Protect has uninstalled this Application then prompted me "This App is Dangerous ....." and also inhibited me from reinstalling it...

• I really depend on this app as my 1st rooting app because I own Lenovo Vibe K5 Note with locked Bootloader and this app is a MIRACLE "for me and other owners for this phone"..

**Comment by JunioJsv** [comment]
The same thing happened to me, probably if I rename the app and change the key this will temporarily resolve this issue.

**Comment by JunioJsv** [comment]
For now try to disable this option inside the play store, then you should be able to install the app again.
![](https://i.imgur.com/e3J7VZA.png)

**Comment by Abdelrhman-AK** [comment]
Thank you so much ❤ ...
