### ISSUE TITLE
Can i flash a file through Flashify or a similar app with this root without bricking the phone? (eu posso flashear algum arquivo pelo flashfy sem brickar o celular?)

### ISSUE THREAD

**Issue by uzeda4** [JunioJsv/mediatek-easy-root#18]
I was thinking about flashing Magisk or maybe even TWRP through the Flashify app, with the root permission that the bootless root app gives me, but i don't know if it will brick my phone (my phone it's a LG K10 Power (M320TV)) and i only have this phone at the moment. So i want to know if someone had already tested this or something similar and what happened.

Eu estava pensando em flashear o Magisk ou até mesmo o TWRP pelo Flashify, com a permissão  do aplicativo de bootless root, mas eu nãos sei se isso vai brickar meu celular (um LG K10 Power(M320TV)) e eu só tenho esse celular no momento. Então eu gostaria de saber se alguem já testou isso ou algo semelhante e no que deu.

**Comment by JunioJsv** [comment]
Se você não sabe oque esta fazendo não é melhor tentar, aliás eu já tentei isso e infelizmente não da certo, a Lg investiu pesado na segurança não da para flashear nada nesse telefone, não a como modificar o /system e etc, por conta disto esse app usa um método de bootless root que não modifica o sistema e somente aproveita as brechas dedicadas nos chipsets da mediatek.

**Comment by uzeda4** [comment]
Tranquilo, agradeço pela resposta ✌️
