### ISSUE TITLE
[request] Auto-run on startup

### ISSUE THREAD

**Issue by telans** [JunioJsv/mediatek-easy-root#2]
Works great with MT6755M

As this is only temporary, it would be nice for it to implement a script somewhere that would auto-run it on boot if we wanted it to. Although thinking, you might need root to do that, and that goes away on reboot...

Side question: I assume that it is unsafe to remount /system as rw?
Assuming the source on xda is correct: 
`LIMITATIONS`
`Cannot modify boot partition unless bootloader is unlocked`
`Cannot modify system/vendor partitions unless boot partition is altered`
`Only Magisk versions up to 18.1 are currently supported--Magisk 19.x has lost the required 'magisk --startup' functionality`

It's a shame because I was really hoping to change /system/apps/ with this

Cheers

**Comment by JunioJsv** [comment]
for sure I'll implement "auto-run on startup". but he wasted without time. If you want to do a pull request by implementing this function I thank you.
dude never tried remont / system for rw. only testing to know :) . if you can, please let me know.

**Comment by telans** [comment]
I'll take a look into it.

`WARNING If you have a device with Android 6 or higher, it likely has dm-verity enabled. On such a device one does not simply remount the system partition as read/write. The remount command will probably fail. But if you succeed in forcing it somehow it will trigger dm-verity, which will result in a very bad day. Your device will become inoperable until you restore the stock system partition.`

From the XDA forum, so I won't be trying that.

**Comment by JunioJsv** [comment]
I just implemented what you ask, in [version 1.0.3^] (https://github.com/JunioJsv/mediatek-easy-root/releases/latest)
