### ISSUE TITLE
Eu posso instalar Magisk Modules com esse root? (Can i install magisk modules with this root?)

### ISSUE THREAD

**Issue by uzeda4** [JunioJsv/mediatek-easy-root#20]
É possível instalar modules no magisk manager com esse root? (Is it possible to install modules in magisk manager with this root?)

**Comment by JunioJsv** [comment]
most do not work properly, I was able to install only these modules 
![Screenshot_2020-01-29-21-04-32](https://user-images.githubusercontent.com/39963398/73408537-4f10e600-42db-11ea-9c5b-676aaab7e3fc.png)
