### ISSUE TITLE
Funciona com MT6735 (Lenovo Vibe C2) ?

### ISSUE THREAD

**Issue by requeijaum** [JunioJsv/mediatek-easy-root#4]
Precisamos de mais testers. Parabéns pelo projeto!

**Comment by JunioJsv** [comment]
Só testando para saber :), aliás se de certo ou não, mande o feedback nessa issue, blz? Vlw flw

**Comment by JunioJsv** [comment]
Ola, teria como você testar com a nova versão 1.0.4 e enviar o log nessa issue?

**Comment by requeijaum** [comment]
Deixa minha namorada trocar de celular (um Redmi Note 7). Estou aguardando os correios entregar. Sem isso: não poderei testar no celular dela.
