### ISSUE TITLE
Não funciona J2 Prime

### ISSUE THREAD

**Issue by Nike277** [JunioJsv/mediatek-easy-root#6]
Por favor Tentem funcionar no J2 Prime, eu até doei para apoiar o trabalho mágico de vocês, por favor.

**Comment by JunioJsv** [comment]
E ai man, tem como você testar novamente com a versão 1.0.4 e mandar o log aqui?

**Comment by Nike277** [comment]
Sim, mas como eu vou mandar o log?

**Comment by Nike277** [comment]
Deu isso no J2 Prime

param1: 0x3000, param2: 0x18040, type: 7
Building symbol table
kallsyms_addresses pa 0x40afb5d0
kallsyms_num_syms 55461, addr_count 55461
kallsyms_names pa 0x40b31880, size 665249
kallsyms_markers pa 0x40bd3f30
kallsyms_token_table pa 0x40bd42a0
kallsyms_token_index pa 0x40bd4610
Patching credentials
Parsing current_is_single_threaded
c02c3f3c: MOVW R0, #0xb3d0
c02c3f40: MOVT R0, #0xc0e6
init_task VA: 0xc0e6b3d0
Potential list_head tasks at offset 0x290
comm swapper/0 at offset 0x400
Found own task_struct at node 1
cred VA: 0xc579f700
Parsing avc_deniedarmv7l machine
selinux_enforcing not found
setns failed: Operation not permitted
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: enforcing  
Root user only
returned 1

**Comment by Nike277** [comment]
Amigo, se quiser pode me usar de cobaia para testar alguma Bluid de teste para o J2 Prime. Tenho WhatsApp e Telegram se precisar só responder que eu mando o número

**Comment by JunioJsv** [comment]
Obrigado, porém eu to sem tempo nenhum por conta da faculdade e trabalho, nem sei se vou continuar mexendo nesse app.

**Comment by Nike277** [comment]
Uma pergunta com esse root eu consigo entrar no ADB de outro celular via comando Terminal?

**Comment by JunioJsv** [comment]
Você teria que arrumar um cabo otg ou conectar via tcp, e de alguma forma instalar os executáveis do adb que vem no sdk android, em seu celular. Procura adb arm no google, talvez tenha algo. Aliás acho que não precisaria de root para executar essa tarefa.

**Comment by 808MT6757CD** [comment]
Funciono perfeito no meu Vernee Mix 2 (MT6757CD)
param1: 0x3000, param2: 0x10000, type: 4
Building symbol table
kallsyms_addresses pa 0x40d6b100
kallsyms_num_syms 65993, addr_count 65993
kallsyms_names pa 0x40dec100, size 815153
kallsyms_markers pa 0x40eb3200
kallsyms_token_table pa 0x40eb3b00
kallsyms_token_index pa 0x40eb3f00
Patching credentials
Parsing current_is_single_threaded
ffffffc0003382c0+50: ADRP x0, 0xffffffc0011ab000
ffffffc0003382c0+54: ADD xd, x0, 3488
init_task VA: 0xffffffc0011abda0
Potential list_head tasks at offset 0x360
comm swapper/0 at offset 0x618
Found own task_struct at node 1
cred VA: 0xffffffc0afe729c0
Parsing avc_denied
ffffffc0002d2dc8+24: ADRP x0, 0xffffffc00156c000
ffffffc0002d2dc8+28: LDR [x0, 2836]
selinux_enforcing VA: 0xffffffc00156cb14
Setting selinux_enforcingarmv8l machine
Retrying...
Retrying...
Retrying...
Retrying...
Could not set selinux
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
returned 0

**Comment by Teeteeuus** [comment]
No J2 prime deu isso

param1: 0x3000, param2: 0x18040, type: 7
Building symbol table
kallsyms_addresses pa 0x40ae6690
kallsyms_num_syms 55252, addr_count 55252
kallsyms_names pa 0x40b1c5f0, size 662604
kallsyms_markers pa 0x40bbe240
kallsyms_token_table pa 0x40bbe5a0
kallsyms_token_index pa 0x40bbe910
Patching credentials
Parsing current_is_single_threaded
c02c3f3c: MOVW R0, #0x5390
c02c3f40: MOVT R0, #0xc0e4
init_task VA: 0xc0e45390
Potential list_head tasks at offset 0x290
comm swapper/0 at offset 0x400
Found own task_struct at node 1
cred VA: 0xc5031080
Parsing avc_deniedarmv7l machine
selinux_enforcing not found
setns failed: Operation not permitted
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: enforcing  
Root user only
returned 1

**Comment by Teeteeuus** [comment]
Pofavor concerta to precisando muito de root mas não quero fazer e o root temporário vai me ajudar muito

**Comment by JunioJsv** [comment]
Vai da não mano, to deixando esse projeto de lado, minha faculdade esta ocupando muito do meu tempo.

**Comment by Teeteeuus** [comment]
_**que decepção 🙁😔**_

**Comment by JunioJsv** [comment]
Fiz esse app visando uso próprio ... ele me atende perfeitamente. Aliás deixei o código aberto visando deixar um ponto de partida, para pessoas como você implementar novas soluções adequadas para seus dispositivos. Um pull request séria bom ...

**Comment by Teeteeuus** [comment]
Mano oque é  mtk-su  não entendo muito dessas coisa

**Comment by Teeteeuus** [comment]
Eu nem sei mexer com essas coisas :(
