### ISSUE TITLE
Maybe safer to close the file before chmodding?

### ISSUE THREAD

**Issue by IDisposable** [JunioJsv/mediatek-easy-root#7]
In https://github.com/JunioJsv/mediatek-easy-root/blob/f9a22cd452de4a6f8d96cda183096bd7ff14c045/app/src/main/java/juniojsv/mediatekeasyroot/TryRoot.kt#L42 we're `chmod` the file that we're just writing to... might be safer to put a `try { } finally { }` around that code that opens, writes, flushes and closes the file **before** we try to change the file mode.

**Comment by JunioJsv** [comment]
Whatever

**Comment by IDisposable** [comment]
Sigh.
